### ISSUE TITLE
Cheat Sheets for Podcast Production

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/administrative#12] opened 2015-03-02 21:56 UTC
Make them look nicer and condensed. Include update on new recording methods with Audacity. Add icons and such.

**Comment by coreysmart92** [comment] 2015-06-03 06:11
Closing because this is a duplicate of New Podcast Cheat Sheet, #64 in the Podcast issues tab.

**Closed by coreysmart92** 2015-06-03 06:11 UTC
